### ISSUE TITLE
Handle image src changes

### ISSUE THREAD

**Issue by ihadeed** [zyramedia/ionic-image-loader#19]
The module currently only handles the initial value that was passed and doesn't handle changes. It should watch any changes in the `src` attribute and act accordingly. 

Nice to have: option to show the spinner while the image is changing

**Comment by ihadeed** [comment]
Fixed in 1.6.0

**Comment by sahildaga95** [comment]
This is still an issue, When the src changes this event works two times and doesn't work the third time. When I relaunch the application the change is reflected.

  ```
          <img-loader [src]="profilePhoto" (load)="onImageLoad($event)"></img-loader>
  
onImageLoad(imgLoader: ImgLoader) {
    console.log('Image Loaded in profile ' + imgLoader);
  }
```

**Comment by ihadeed** [comment]
Please open a new issue with steps to reproduce this.

Also, double check to see if your parent component(s) have any change detection issues. (i.e... change detection strategies, what is causing the link to change... etc)

Run `NgZone.isInAngularZone()` before updating the image URL to make sure you're always in the zone.

**Comment by sahildaga95** [comment]
@ihadeed - If the change detection was an issue then it wouldn't have worked the first two times right ?

**Comment by ihadeed** [comment]
Yeah... I'm just saying to double check in case something else that is not in the zone is updating the image the third time. Not sure what your code looks like.

**Comment by sahildaga95** [comment]
It is giving true every time I logged it before changing the image URL.
